name: Dump
description: Dump the context and date

inputs:
  test-input-word:
    require: false

outputs:
  dumped-date:
    value: ${{ steps.current.outputs.date }}

runs:
  using: composite
  steps:
    - id: current
      shell: bash
      run: echo "date=$(date)" >> ${GITHUB_OUTPUT}
