name: Dump
on: push

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dump
        with:
          enable-context: 'true'
          test-input-word: 'test_message'
      - run: echo "${DATE}"
        env: 
          DATE: ${{ steps.dump.outputs.dump-date }}