name: Comment
on: pull_request

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dump
        with:
          enable-context: 'true'
          test-input-word: 'test_message'
      - run: echo ${DATE}
        env:
          DATE: ${{ steps.current.outputs.dump-date }}
      - run: echo ${TEST_WORD}
        env:
          TEST_WORD: ${{ steps.test-input.outputs.dump-test-input-word }}