name: ZZZZZZZZZZ

on: push
jobs:
  XXXXXXXXXXXXXX:
    runs-on: ubuntu-latest
    steps:
      - name: YYYYYYYYYYYYYYY
        run: echo "Hello World"
  AAAAAAAAAAAAAA:
    runs-on: ubuntu-latest
    steps:
      - name: BBBBBBBBBBBBBB
        run: echo "Hello World"