name: Hello

on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep FUNC
        env:
          FUNC_CONTAINS: ${{ contains('hello', 'll')}}
          FUNC_STARTSWITH: ${{ startsWith('hello', 'he') }}
          FUNC_ENDSWITH: ${{ endsWith('hello', 'lo') }}
          FUNC_ENDSWITH1: ${{ endsWith('hello', 'l') }}
          FUNC_FORMAT: ${{ format('{0}, {1}.', 'Hello','world') }}
          FUNC_JOIN: ${{ join(github.event.*.html_url, ',') }}