name: "Hello world"

on: 
    push:

jobs:
    sample:
        name: Hello world job
        runs-on: ubuntu-latest
        steps:
            - name: hello world test actions
              id: hello
              run: 
                echo "Hello world"
                echo "actions practis"