name: Hello

on: 
  push:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful wording

jobs:
  hello:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  workfluow_dispatch_test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }} World"