name: ZZZZZZZZZZ

on: push
jobs:
  shares:
    runs-on: ubuntu-latest
    steps:
      - id: source1
        run: echo "result1=Hello" >> $GITHUB_OUTPUT
      - id: source2
        run: echo "result2=World" >> $GITHUB_OUTPUT
      - id: target1
        env:
          RESULT1: ${{ steps.source1.outputs.result1}}
        run: echo ${RESULT1}
      - id: target2
        env: 
          RESULT2: ${{ steps.source2.outputs.result2}}
        run: echo ${RESULT2}