name: Hello

on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - run: echo "hello failure"
        if: ${{ failure()}}
      - run: exit 1
      - run: echo "hello always"
        if: ${{ always()}}