name: "Hello world"

on: 
    push:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
      - name: cat workflows
        id: cat
        run: cat .github/workflows/hellowworld.yml
